SET WIDTH=03
SET HEIGHT=03
SET TYPE=BP
SET EXTRA=NONE

SET SKIP= 
REM SET SKIP=REM 

SET CALLSTYLE=CALL

SET WIDTH=03
SET HEIGHT=03
SET BEARING=606
SET PART=%TYPE%-%BEARING%-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=05
SET HEIGHT=05
SET BEARING=6810
SET PART=%TYPE%-%BEARING%-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=04
SET HEIGHT=04
SET BEARING=6806
SET PART=%TYPE%-%BEARING%-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat
