SET WIDTH=03
SET HEIGHT=01
SET TYPE=JA
SET EXTRA=NONE

SET SKIP= 
REM SET SKIP=REM 

SET CALLSTYLE=CALL

SET WIDTH=01
SET PART=%TYPE%-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=02
SET PART=%TYPE%-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=03
SET PART=%TYPE%-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=04
SET PART=%TYPE%-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=05
SET PART=%TYPE%-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=06
SET PART=%TYPE%-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=03
SET HEIGHT=02
SET PART=%TYPE%-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat
