SET WIDTH=03
SET HEIGHT=00
SET TYPE=PL
SET EXTRA=NONE

SET SKIP= 
REM SET SKIP=REM 

SET CALLSTYLE=CALL

SET GENE=
REM SET GENE=3DPR

SET WIDTH=01
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=02
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=02
SET HEIGHT=02
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=03
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=03
SET HEIGHT=01
SET THICK=6
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=03
SET HEIGHT=01
SET THICK=9
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=03
SET HEIGHT=01
SET THICK=12
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat


SET WIDTH=03
SET HEIGHT=02
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=03
SET HEIGHT=03
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=04
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=04
SET HEIGHT=02
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=04
SET HEIGHT=03
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=04
SET HEIGHT=04
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=05
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=05
SET HEIGHT=01
SET THICK=6
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=05
SET HEIGHT=01
SET THICK=9
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=05
SET HEIGHT=01
SET THICK=12
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=05
SET HEIGHT=02
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=05
SET HEIGHT=03
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=05
SET HEIGHT=04
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=05
SET HEIGHT=05
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=06
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=06
SET HEIGHT=02
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=06
SET HEIGHT=03
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=06
SET HEIGHT=04
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=06
SET HEIGHT=05
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=06
SET HEIGHT=06
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=07
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=07
SET HEIGHT=03
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=07
SET HEIGHT=05
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=07
SET HEIGHT=07
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=08
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=08
SET HEIGHT=03
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=08
SET HEIGHT=05
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=08
SET HEIGHT=08
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=09
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=09
SET HEIGHT=03
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=09
SET HEIGHT=05
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=09
SET HEIGHT=09
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=10
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=10
SET HEIGHT=10
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=11
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat


SET WIDTH=11
SET HEIGHT=01
SET THICK=6
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=11
SET HEIGHT=01
SET THICK=9
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=11
SET HEIGHT=01
SET THICK=12
%SKIP%%CALLSTYLE% OOBB-generate-PL-TH.bat


SET WIDTH=12
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=12
SET HEIGHT=12
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=14
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=14
SET HEIGHT=14
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=15
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=15
SET HEIGHT=03
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=15
SET HEIGHT=05
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=15
SET HEIGHT=15
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=20
SET HEIGHT=20
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=25
SET HEIGHT=01
SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

REM Not generated due to taking a long time.
REM SET WIDTH=25
REM SET HEIGHT=25
REM SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

REM SET WIDTH=30
REM SET HEIGHT=30
REM SET PART=PL-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat




