REM ######  OOBB GENERATE FILES  ######
REM ###################################
REM 





SET DIRECTORY=parts\%TYPE%\%PART%\

SET EXTRAFILESTRING=-%EXTRA%

IF %EXTRA%==NONE SET EXTRAFILESTRING=

SET FILE=OOBB-%PART%%EXTRAFILESTRING%
SET FILE3DPR=OOBB-%PART%%EXTRAFILESTRING%-3DPR
SET FILEMD=README.md

SET FILEFULL=%DIRECTORY%%FILE%
SET FILEFULL3DPR=%DIRECTORY%%FILE3DPR%
SET FILEFULLMD=%DIRECTORY%%FILEMD%

SET NAME=%PART%

mkdir %DIRECTORY%

SET MODE=%PART%

SET STYLE=3DPR
del %FILEFULL3DPR%.stl
openscad -o %FILEFULL3DPR%.stl -D "o=\"3DPR\";w=%WIDTH%;h=%HEIGHT%;m=\"%MODE%\";extra=\"%EXTRA%\"" OOBB-generate-%STYLE%.scad
