SET WIDTH=03
SET HEIGHT=03
SET TYPE=SP
SET EXTRA=NONE

SET SKIP= 
REM SET SKIP=REM 

SET CALLSTYLE=CALL

SET PART=SP-GM1-03
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET PART=SP-GM1-06
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat
