SET WIDTH=03
SET HEIGHT=03
SET TYPE=HL

SET SKIP= 
SET SKIP=REM 

SET CALLSTYLE=CALL

SET GENE=
SET GENE=3DPR

SET PART=HL-RC-03-03
SET EXTRA=NONE
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET PART=HL-CN-03-03
SET EXTRA=NONE
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat


SET HEIGHT=03
SET WIDTH=03
SET TYPE=HL
SET PART=HL-GM1-%WIDTH%-%HEIGHT%
SET EXTRA=TOP
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=BOTTOM
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=NONE
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat


SET HEIGHT=03
SET WIDTH=03
SET TYPE=HL
SET PART=HL-GM1-%WIDTH%-%HEIGHT%-BP6803
SET EXTRA=TOP
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=NONE
%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat


SET HEIGHT=06
SET WIDTH=05
SET TYPE=HL
SET PART=HL-B4AA-%HEIGHT%-%WIDTH%
SET EXTRA=NONE
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat