SET WIDTH=03
SET HEIGHT=00
SET TYPE=CI
SET EXTRA=NONE

SET SKIP= 
REM SET SKIP=REM 

SET CALLSTYLE=CALL

SET WIDTH=01
SET PART=CI-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=03
SET PART=CI-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=05
SET PART=CI-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=07
SET PART=CI-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=09
SET PART=CI-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=11
SET PART=CI-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=15
SET PART=CI-%WIDTH%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

SET WIDTH=03
SET PART=CI-%WIDTH%-GM1
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART.bat

