SET WIDTH=03
SET HEIGHT=03
SET TYPE=BP
SET EXTRA=NONE

SET SKIP= 
SET SKIP=REM 

SET GENE=
SET GENE=3DPR

SET CALLSTYLE=CALL

SET WIDTH=03
SET HEIGHT=03
SET BEARING=606
SET EXTRA=NONE
SET PART=%TYPE%-%BEARING%-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=HALF
%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=TOP
%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=MIDDLE
%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat


SET WIDTH=03
SET HEIGHT=03
SET BEARING=6803
SET EXTRA=NONE
SET PART=%TYPE%-%BEARING%-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=HALF
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=TOP
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
SET EXTRA=MIDDLE
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat


SET WIDTH=05
SET HEIGHT=05
SET BEARING=6810
SET PART=%TYPE%-%BEARING%-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET WIDTH=04
SET HEIGHT=04
SET BEARING=6806
SET PART=%TYPE%-%BEARING%-%WIDTH%-%HEIGHT%
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
