SET WIDTH=03
SET HEIGHT=03
SET TYPE=SP
SET EXTRA=NONE

SET SKIP= 
REM SET SKIP=REM 

SET CALLSTYLE=CALL

SET GENE=
REM SET GENE=3DPR



REM NOT THE ANSWER
REM SET PART=SP-GM1-03
REM %SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

REM SET PART=SP-GM1-06
REM %SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat
