SET WIDTH=03
SET HEIGHT=03
SET TYPE=WH

SET SKIP= 
REM SET SKIP=REM 

SET CALLSTYLE=CALL

SET GENE=
SET GENE=3DPR

SET PART=WH-03-GM1
SET EXTRA=NONE
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat

SET PART=WH-03-N20
SET EXTRA=NONE
%SKIP%%CALLSTYLE% AAA-OOBB-generate-PART%GENE%.bat