REM ######  OOBB GENERATE FILES  ######
REM ###################################
REM 


SET WIDTH=0
SET HEIGHT=0
SET EXTRA=NONE


SET TYPE=TEST
SET PART=TEST-SERVOHORN
REM CALL OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-BEARING6704
CALL OOBB-generate-NICHE-generic.bat
