SET WIDTH=0
SET HEIGHT=0
SET EXTRA=NONE
SET CALLSTYLE=START

SET TYPE=HL
SET PART=HL-SM-03-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDER
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=BASE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=NOHORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET EXTRA=NONE