REM ######  OOBB GENERATE FILES  ######
REM ###################################
REM 

SET CALLSTYLE=CALL

SET WIDTH=0
SET HEIGHT=0
SET EXTRA=NONE


SET TYPE=TEST
SET PART=TEST-SERVOHORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-SERVOMICROHORNCATCH
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-SERVOMICROHORNCATCHSINGLE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-SERVOMICROHORNCATCHSINGLECONTINUOUS
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-COUNTERSINKM3
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-SOCKETHEADM3
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-FIRSTLAYERLIP
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-BEARING6704-OUTSIDE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET TYPE=TEST
SET PART=TEST-BEARING6704-MIDDLE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET TYPE=TEST
SET PART=TEST-BEARING6803-OUTSIDE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-BEARING6803-MIDDLE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET TYPE=TEST
SET PART=TEST-OOEBNORMAL
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


