REM ######  OOBB GENERATE FILES  ######
REM ###################################
REM 

SET CALLSTYLE=CALL

SET WIDTH=0
SET HEIGHT=0
SET EXTRA=NONE

SET TYPE=BP
SET PART=BP-606-03-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=SANDWICH
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=NONE


SET TYPE=BP
SET PART=BP-6810-05-05
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=BP
SET PART=BP-6806-04-04
%CALLSTYLE% OOBB-generate-NICHE-generic.bat



SET TYPE=HL
SET PART=HL-N17-05-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=HL
SET PART=HL-PZ-05-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=HL
SET PART=HL-PC-03-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET TYPE=HL
SET PART=HL-SM-03-03-6704
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDER
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDERA
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDERB
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET EXTRA=BRACKET
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=BASE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET EXTRA=NOHORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET TYPE=HL
SET PART=HL-SM-03-03-6803
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDER
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDERA
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDERB
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=BRACKET
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=BASE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET EXTRA=NOHORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=HL
SET PART=HL-SE-05-03-6803
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDER
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDERA
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDERB
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=BRACKET
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=BASE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET EXTRA=NOHORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET EXTRA=NONE




SET TYPE=CI
SET PART=CI-03-CA-FL
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=HL
SET PART=HL-B2X-07-04
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=HL
SET PART=HL-B1X-09-02
%CALLSTYLE% OOBB-generate-NICHE-generic.bat






