REM ######  OOBB GENERATE FILES  ######
REM ###################################
REM 

SET CALLSTYLE=CALL

SET HEIGHT=00
SET EXTRA=NONE


REM Niche items

REM %CALLSTYLE% OOBB-generate-NICHE.bat
START OOBB-generate-NICHE.bat

REM Test Items

REM %CALLSTYLE% OOBB-generate-TEST.bat
START OOBB-generate-TEST.bat

REM CI (Circles)



SET WIDTH=01
%CALLSTYLE% OOBB-generate-CI.bat
SET WIDTH=03
%CALLSTYLE% OOBB-generate-CI.bat
SET WIDTH=05
%CALLSTYLE% OOBB-generate-CI.bat
SET WIDTH=07
%CALLSTYLE% OOBB-generate-CI.bat
SET WIDTH=09
%CALLSTYLE% OOBB-generate-CI.bat
SET WIDTH=11
%CALLSTYLE% OOBB-generate-CI.bat
SET WIDTH=15
%CALLSTYLE% OOBB-generate-CI.bat

REM WH (Wheels)

SET WIDTH=03
%CALLSTYLE% OOBB-generate-WH.bat
SET WIDTH=03
%CALLSTYLE% OOBB-generate-WHS.bat
SET WIDTH=05
%CALLSTYLE% OOBB-generate-WH.bat
SET WIDTH=05
%CALLSTYLE% OOBB-generate-WHS.bat
SET WIDTH=07
%CALLSTYLE% OOBB-generate-WH.bat






REM JA (Jacks)

SET WIDTH=01
%CALLSTYLE% OOBB-generate-JA.bat

SET WIDTH=02
%CALLSTYLE% OOBB-generate-JA.bat

SET WIDTH=03
%CALLSTYLE% OOBB-generate-JA.bat

SET WIDTH=04
%CALLSTYLE% OOBB-generate-JA.bat

SET WIDTH=05
%CALLSTYLE% OOBB-generate-JA.bat

SET WIDTH=06
%CALLSTYLE% OOBB-generate-JA.bat

SET WIDTH=07
%CALLSTYLE% OOBB-generate-JA.bat



REM CP (Captive Plates)

SET WIDTH=03
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-CP.bat


REM PL (Plates)

SET WIDTH=01
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=02
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=02
SET HEIGHT=02
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=03
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=03
SET HEIGHT=02
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=03
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=04
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=04
SET HEIGHT=02
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=04
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=04
SET HEIGHT=04
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=05
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=05
SET HEIGHT=01
SET THICK=6
%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=05
SET HEIGHT=01
SET THICK=9
%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=05
SET HEIGHT=01
SET THICK=12
%CALLSTYLE% OOBB-generate-PL-TH.bat

SET WIDTH=05
SET HEIGHT=02
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=05
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=05
SET HEIGHT=04
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=05
SET HEIGHT=05
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=06
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=06
SET HEIGHT=02
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=06
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=06
SET HEIGHT=04
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=06
SET HEIGHT=05
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=06
SET HEIGHT=06
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=07
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=07
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=07
SET HEIGHT=05
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=07
SET HEIGHT=07
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=08
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=08
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=08
SET HEIGHT=05
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=08
SET HEIGHT=08
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=09
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=09
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=09
SET HEIGHT=05
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=09
SET HEIGHT=09
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=10
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=10
SET HEIGHT=10
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=11
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=12
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=12
SET HEIGHT=12
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=14
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=14
SET HEIGHT=14
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=15
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=15
SET HEIGHT=03
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=15
SET HEIGHT=05
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=15
SET HEIGHT=15
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=20
SET HEIGHT=20
%CALLSTYLE% OOBB-generate-PL.bat

SET WIDTH=25
SET HEIGHT=01
%CALLSTYLE% OOBB-generate-PL.bat

REM Not generated due to taking a long time.
REM SET WIDTH=25
REM SET HEIGHT=25
REM %CALLSTYLE% OOBB-generate-PL.bat

REM SET WIDTH=30
REM SET HEIGHT=30
REM %CALLSTYLE% OOBB-generate-PL.bat



