REM ######  OOBB GENERATE FILES  ######
REM ###################################
REM 

SET CALLSTYLE=START

SET WIDTH=0
SET HEIGHT=0
SET EXTRA=NONE


SET TYPE=TEST
SET PART=TEST-SERVOHORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-BEARING6704
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=TEST
SET PART=TEST-COUNTERSINKM3
%CALLSTYLE% OOBB-generate-NICHE-generic.bat
