SET WIDTH=0
SET HEIGHT=0
SET EXTRA=NONE

SET CALLSTYLE=START


REM SET TYPE=HL
REM SET PART=HL-B2X-07-05
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat

REM SET WIDTH=03
REM SET HEIGHT=03
REM %CALLSTYLE% OOBB-generate-CP.bat


REM SET TYPE=HL
REM SET PART=HL-PC-03-03
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat



REM WH (Wheels)

REM SET WIDTH=03
REM %CALLSTYLE% OOBB-generate-WH.bat
REM SET WIDTH=05
REM %CALLSTYLE% OOBB-generate-WH.bat
REM SET WIDTH=07
REM %CALLSTYLE% OOBB-generate-WH.bat





REM SET TYPE=HL
REM SET PART=HL-SM-03-03-6704
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat

REM SET EXTRA=HOLDER
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat

REM SET EXTRA=BRACKET
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat

REM SET EXTRA=BASE
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat

REM SET EXTRA=HORN
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat


REM SET EXTRA=NOHORN
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET TYPE=HL
SET PART=HL-SM-03-03-6803
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDER
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

REM SET EXTRA=BRACKET
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat

REM SET EXTRA=BASE
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat

REM SET EXTRA=HORN
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat


REM SET EXTRA=NOHORN
REM %CALLSTYLE% OOBB-generate-NICHE-generic.bat


REM SET EXTRA=NONE


