REM ######  OOBB GENERATE FILES  ######
REM ###################################
REM 

SET CALLSTYLE=START

SET WIDTH=0
SET HEIGHT=0
SET EXTRA=NONE

SET TYPE=BP
SET PART=BP-606-03-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=SANDWICH
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=NONE


SET TYPE=BP
SET PART=BP-6810-05-05
%CALLSTYLE% OOBB-generate-NICHE-generic.bat



SET TYPE=HL
SET PART=HL-N17-05-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET TYPE=HL
SET PART=HL-PZ-05-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET TYPE=HL
SET PART=HL-SM-03-03
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HOLDER
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=BASE
%CALLSTYLE% OOBB-generate-NICHE-generic.bat

SET EXTRA=HORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET EXTRA=NOHORN
%CALLSTYLE% OOBB-generate-NICHE-generic.bat


SET EXTRA=NONE




SET TYPE=CI
SET PART=CI-03-CA-FL
%CALLSTYLE% OOBB-generate-NICHE-generic.bat





